name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install nasm clang-format -y

      - name: Check format
        run: make check-format

      - name: Build
        run: make

      - name: Run tests
        run: make tests
